# Generated by Django 5.1.6 on 2025-10-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_inventory', 'Low Inventory'), ('delayed_shipment', 'Delayed Shipment'), ('demand_surge', 'Demand Surge'), ('supplier_issue', 'Supplier Issue')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('analyzing', 'Analyzing'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='detected', max_length=20)),
                ('current_stock', models.IntegerField(blank=True, null=True)),
                ('alert_data', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_alerts', to='app.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_alerts', to='app.product')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_inventory_level', models.IntegerField(default=10)),
                ('warning_inventory_level', models.IntegerField(default=20)),
                ('reorder_point', models.IntegerField(default=15)),
                ('safety_stock', models.IntegerField(default=5)),
                ('auto_resolution_enabled', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=True)),
                ('check_interval_minutes', models.IntegerField(default=5)),
                ('notification_emails', models.JSONField(default=list)),
                ('slack_webhook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('execution_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='started', max_length=20)),
                ('root_cause', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('analysis_data', models.JSONField(default=dict)),
                ('solution_data', models.JSONField(default=dict)),
                ('orchestration_data', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='app.agentalert')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('step_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='app.agentexecution')),
            ],
            options={
                'ordering': ['execution', 'step_number'],
            },
        ),
        migrations.AddIndex(
            model_name='agentalert',
            index=models.Index(fields=['alert_type', 'status'], name='app_agental_alert_t_626e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentalert',
            index=models.Index(fields=['company', 'detected_at'], name='app_agental_company_41a84e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentworkflowstep',
            unique_together={('execution', 'step_number')},
        ),
    ]
