# Generated by Django 5.1.6 on 2025-10-22 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_agentalert_agentconfiguration_agentexecution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('gmail', 'Gmail'), ('slack', 'Slack'), ('google_sheets', 'Google Sheets'), ('google_calendar', 'Google Calendar'), ('google_drive', 'Google Drive')], max_length=50)),
                ('integration_name', models.CharField(help_text='Custom name for this integration', max_length=100)),
                ('status', models.CharField(choices=[('not_configured', 'Not Configured'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='not_configured', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config_data', models.JSONField(default=dict, help_text='Integration-specific configuration')),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('composio_entity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'integration_type', 'integration_name')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('send_message', 'Send Message'), ('update_sheet', 'Update Sheet'), ('create_event', 'Create Calendar Event'), ('upload_file', 'Upload File'), ('webhook', 'Webhook Call')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.integrationconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='app_integra_created_176031_idx'), models.Index(fields=['integration', 'status'], name='app_integra_integra_261cbf_idx')],
            },
        ),
    ]
